name: Setup Java and Maven Environment

steps:
  - name: Checkout code
    uses: actions/checkout@v4

  - name: Set up JDK 21
    uses: actions/setup-java@v4
    with:
      java-version: '21'
      distribution: 'temurin'
      cache: 'maven'

  - name: Set up Maven 3.9.11
    uses: stCarolas/setup-maven@v5
    with:
      maven-version: '3.9.11'

  - name: Package JAR (skip tests)
    run: mvn clean package -DskipTests -B -V

  - name: Copy JAR to standard location
    run: |
      mkdir -p /home/runner/target
      cp target/mcp-osgi-server-1.0.0-SNAPSHOT.jar /home/runner/target/
      echo "MCP server JAR copied to /home/runner/target/mcp-osgi-server-1.0.0-SNAPSHOT.jar"
