name: Build MCP OSGi Server

on:
  workflow_call:
    outputs:
      jar-path:
        description: "Path to the built MCP server JAR file"
        value: ${{ jobs.build.outputs.jar-path }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      jar-path: ${{ steps.build.outputs.jar-path }}
    
    steps:
    - name: Checkout MCP OSGi repository
      uses: actions/checkout@v4
      with:
        repository: laeubi/mcp_osgi
        path: mcp_osgi
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'maven'
        
    - name: Build MCP server JAR
      id: build
      run: |
        cd mcp_osgi
        mvn clean package -DskipTests -B -V
        JAR_PATH="${GITHUB_WORKSPACE}/mcp_osgi/target/mcp-osgi-server-1.0.0-SNAPSHOT.jar"
        echo "jar-path=${JAR_PATH}" >> $GITHUB_OUTPUT
        echo "Built JAR at: ${JAR_PATH}"
        
    - name: Upload MCP server JAR
      uses: actions/upload-artifact@v4
      with:
        name: mcp-osgi-server
        path: mcp_osgi/target/mcp-osgi-server-1.0.0-SNAPSHOT.jar
        retention-days: 90
